version: "3.6"

x-logging-common: &logging-common
  logging:
    options:
      max-size: "10m"
      max-file: "4"

services:
  db:
    container_name: postgres
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
    env_file:
      - ./.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER} -d $${DB_NAME}"]
      interval: 1s
      timeout: 5s
      retries: 10
    restart: always
    <<: *logging-common

  api:
    build: .
    container_name: api
    image: api
    command: >
      bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - ./.env
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 8000:8000
    restart: always
    <<: *logging-common

volumes:
  postgres_data:
