"""init_db

Revision ID: 6ecf0b30f499
Revises: 
Create Date: 2024-05-06 20:06:48.102775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ecf0b30f499'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_disease',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories_disease')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_disease_name'))
    )
    op.create_table('clients',
    sa.Column('date_birthday', sa.Date(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('middle_name', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients')),
    sa.UniqueConstraint('first_name', 'last_name', 'middle_name', name='uq_client_full_name')
    )
    op.create_table('professions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professions')),
    sa.UniqueConstraint('name', name=op.f('uq_professions_name'))
    )
    op.create_table('diseases',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=10000), nullable=False),
    sa.Column('category_disease_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_disease_id'], ['categories_disease.id'], name=op.f('fk_diseases_category_disease_id_categories_disease')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diseases')),
    sa.UniqueConstraint('name', name=op.f('uq_diseases_name'))
    )
    op.create_index(op.f('ix_diseases_category_disease_id'), 'diseases', ['category_disease_id'], unique=False)
    op.create_table('doctors',
    sa.Column('date_start_work', sa.Date(), nullable=False),
    sa.Column('date_birthday', sa.Date(), nullable=False),
    sa.Column('profession_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('middle_name', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], name=op.f('fk_doctors_profession_id_professions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctors')),
    sa.UniqueConstraint('first_name', 'last_name', 'middle_name', name='uq_doctor_names')
    )
    op.create_index(op.f('ix_doctors_profession_id'), 'doctors', ['profession_id'], unique=False)
    op.create_table('anappointments',
    sa.Column('start_date_appointment', sa.DateTime(), nullable=False),
    sa.Column('end_date_appointment', sa.DateTime(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_anappointments_client_id_clients'), ondelete='SET NULl'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_anappointments_doctor_id_doctors'), ondelete='SET NULl'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anappointments'))
    )
    op.create_index(op.f('ix_anappointments_client_id'), 'anappointments', ['client_id'], unique=False)
    op.create_index(op.f('ix_anappointments_doctor_id'), 'anappointments', ['doctor_id'], unique=False)
    op.create_table('diagnosis',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('date_closed', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='statuschoices'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_diagnosis_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_diagnosis_doctor_id_doctors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnosis'))
    )
    op.create_index(op.f('ix_diagnosis_client_id'), 'diagnosis', ['client_id'], unique=False)
    op.create_index(op.f('ix_diagnosis_doctor_id'), 'diagnosis', ['doctor_id'], unique=False)
    op.create_table('disease_diagnosis',
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis.id'], name=op.f('fk_disease_diagnosis_diagnosis_id_diagnosis'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], name=op.f('fk_disease_diagnosis_disease_id_diseases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('disease_id', 'diagnosis_id', 'id', name=op.f('pk_disease_diagnosis'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disease_diagnosis')
    op.drop_index(op.f('ix_diagnosis_doctor_id'), table_name='diagnosis')
    op.drop_index(op.f('ix_diagnosis_client_id'), table_name='diagnosis')
    op.drop_table('diagnosis')
    op.drop_index(op.f('ix_anappointments_doctor_id'), table_name='anappointments')
    op.drop_index(op.f('ix_anappointments_client_id'), table_name='anappointments')
    op.drop_table('anappointments')
    op.drop_index(op.f('ix_doctors_profession_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_diseases_category_disease_id'), table_name='diseases')
    op.drop_table('diseases')
    op.drop_table('professions')
    op.drop_table('clients')
    op.drop_table('categories_disease')
    # ### end Alembic commands ###
