"""added_new_table

Revision ID: de7d61ff62ae
Revises: 6ecf0b30f499
Create Date: 2024-05-18 07:55:54.752148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de7d61ff62ae'
down_revision: Union[str, None] = '6ecf0b30f499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('start_date_appointment', sa.DateTime(), nullable=False),
    sa.Column('end_date_appointment', sa.DateTime(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_appointments_client_id_clients'), ondelete='SET NULl'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_appointments_doctor_id_doctors'), ondelete='SET NULl'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_index(op.f('ix_appointments_client_id'), 'appointments', ['client_id'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.drop_index('ix_anappointments_client_id', table_name='anappointments')
    op.drop_index('ix_anappointments_doctor_id', table_name='anappointments')
    op.drop_table('anappointments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anappointments',
    sa.Column('start_date_appointment', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date_appointment', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='fk_anappointments_client_id_clients', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name='fk_anappointments_doctor_id_doctors', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_anappointments')
    )
    op.create_index('ix_anappointments_doctor_id', 'anappointments', ['doctor_id'], unique=False)
    op.create_index('ix_anappointments_client_id', 'anappointments', ['client_id'], unique=False)
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_client_id'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
